name: Run Cucumber Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: Windows

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '17'

    - run: mvn clean test
